services:
  postgres:
    image: "bitnami/postgresql:latest"
    container_name: API-helpdesk
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: helpdesk